dataset: isic
arch: resnet50
train_type: supervised #which train type we will perform: SSL or supervised
weight_type: imgnet_bt_pretrained #random,imgnet_sup_pretrained, imgnet_bt_pretrained, dermnet_bt_pretrained
learn_type: semi_supervised  #or supervised semi_supervised, linear_evaluation
size: 256 #size of the image
n_in: 3
bs: 64 #batch size for training
bs_test: 64 #batch size for testing
sup_augs: supervised_isic_augmentations # other options: bt_`dataset_name`_aug_pipelines
wd: 0.0
freeze_epochs: 1
num_it: 100
pct_dataset_train: 1.0 #may set to 0.01, 0.1, 1.0 e.g. for isic dataset
pct_dataset_test: 1.0  #generally this is 1.0 outside of testing code
epochs: 40  # epochs to train BT variant
num_runs: 35 #Number of runs to perform
load_pretrained_path: none #/content/drive/MyDrive/Experiments/barlow_twins/SSL/dermnet/resnet50/970b7b4b/trained_encoder_epoch_499.pth
