dataset: isic
arch: resnet50
train_type: supervised #which train type we will perform: SSL or supervised
weight_type: imgnet_bt_isicufesdermnet_bt_pretrained #random,imgnet_sup_pretrained, imgnet_bt_pretrained, dermnet_bt_pretrained,imgnet_bt_dermnet_bt_pretrained 
learn_type: semi_supervised  #or standard semi_supervised, linear_evaluation
size: 256 #size of the image
n_in: 3
bs: 64 #batch size for training
bs_test: 64 #batch size for testing
sup_augs: supervised_isic_augmentations # other options: bt_`dataset_name`_aug_pipelines
wd: 0.0
freeze_epochs: 1 #set to 2, 4 when pct_dataset_train is 0.5, 0.25
num_it: 100
pct_dataset_train: 1.0 #set to 0.5,0.25 as well
pct_dataset_test: 1.0  #generally this is 1.0 outside of testing code
epochs: 40  # epochs to train BT variant
num_runs: 35 #Number of runs to perform
load_pretrained_path: /content/drive/MyDrive/Experiments/barlow_twins/SSL/isicufesdermnet/resnet50/5b3a3ef1/trained_encoder_epoch_99.pth
