dataset: cifar10
arch: resnet18
train_type: SSL #which train type we will perform: SSL or supervised
weight_type: random #random,supervised_pretrained, bt_pretrained
size: 32 #size of the image
n_in: 3
bs: 128 #batch size for training
ps: 512  # size of projector dimension
hs: 512  # size of hidden dimension
bt_augs: bt_cifar10_aug_pipelines # other options: bt_`dataset_name`_aug_pipelines
model_type: barlow_twins  # barlow_twins or sparse_barlow_twins
lmb: none #0.001953125 #this comes from ps generally
sparsity_level: none
wd: 0.0000015 #1.5*1e-6 which is the deault in the paper. We may have to ablate as a control to our idea though
freeze_epochs: 1
epochs: 1000  # epochs to train BT variant

