dataset: cifar10
arch: smallres
train_type: supervised #which train type we will perform: SSL or supervised
weight_type: random #random,imgnet_sup_pretrained, imgnet_bt_pretrained, dermnet_bt_pretrained
learn_type: standard  #or supervised semi_supervised, linear_evaluation
size: 32 #size of the image
n_in: 3
bs: 64 #batch size for training
bs_test: 64 #batch size for testing
sup_augs: supervised_cifar10_augmentations # other options: bt_`dataset_name`_aug_pipelines
wd: 0.0
freeze_epochs: 1
num_it: 10
pct_dataset_train: 0.01 #may set to 0.01, 0.1, 1.0 e.g. for isic dataset
pct_dataset_test: 0.1  #generally this is 1.0 outside of testing code
epochs: 1  # epochs to train BT variant
num_runs: 1 #Number of runs to perform

