dataset: isic
arch: resnet50
train_type: supervised #which train type we will perform: SSL or supervised
weight_type: dermnet_bt_pretrained #random,imgnet_sup_pretrained, imgnet_bt_pretrained, dermnet_bt_pretrained
size: 256 #size of the image
n_in: 3
bs: 64 #batch size for training
bs_test: 64 #batch size for testing
augs: supervised_isic_augmentations # other options: bt_`dataset_name`_aug_pipelines
model_type: semi_supervised  #or semi_supervised, supervised_learning
wd: 0.0 
epochs: 40  # epochs to train BT variant
freeze_epochs: none 
num_runs: 10 #Number of runs to perform

