dataset: cifar10
arch: cifar_resnet18 #changed in future
train_type: supervised #which train type we will perform: SSL or supervised
weight_type: cifar10_pretrained #random,imgnet_sup_pretrained, imgnet_bt_pretrained, dermnet_bt_pretrained
learn_type: linear_evaluation  #or supervised semi_supervised, linear_evaluation
size: 32 #size of the image
n_in: 3
bs: 256 #batch size for training
bs_test: 256 #batch size for testing
sup_augs: supervised_cifar10_augmentations # other options: bt_`dataset_name`_aug_pipelines
deterministic_test: True 
wd: 0.000001
freeze_epochs: none
num_it: 100
pct_dataset_train: 1.0 #may set to 0.01, 0.1, 1.0 e.g. for isic dataset
pct_dataset_test: 1.0  #generally this is 1.0 outside of testing code
epochs: 50  # epochs to train BT variant
num_runs: 1 #Number of runs to perform
load_pretrained_path: /content/drive/MyDrive/Experiments/vicreg/SSL/cifar10/cifar_resnet18/76f55f30/trained_left_encoder_epoch_499.pth
